shot:
  # Actual and expected directories
  imageDirectories:
    actual: src/test/resources/shot_images/actual/
    expected: src/test/resources/shot_images/expected/

  # Retake shot settings
  retakeShot:
    count: 3
    interval: 1000

  # Multi-Reference settings
  multiReference:
    # Should be >= 1
    count: 3
    interval: 1000

  # Flags
  flags:
    saveShotImage: true
    saveOnTheFlyReference: true
    supportFluentNaming: false
    resizeShotImageToMatchReferenceImageSize: true
    forceResizeWindowToMatchReference: true

  # Techniques
  techniques:
    - technique: SSI
      threshold: 0.90
      comparisonOperation: GREATER

    - technique: MSE
      threshold: 30.0
      comparisonOperation: LESS