shot:
  actual-path: src/test/resources/shot_images/actual/
  expected-path: src/test/resources/shot_images/expected/

  retake-shot: 3
  retake-shot-interval: 1000
  # >= 1
  multi-ref: 3
  multi-ref-interval: 1000

  flags:
    save-shot: true
    save-on-fly-ref: true
    support-fluent: false
    resize-ref-image-to-match-shot-image-size: true
    force-resize-window-to-match-the-reference: true

  techniques:
    - technique: SSI
      threshold: 0.90
      operation: GREATER

    - technique: MSE
      threshold: 30.0
      operation: LESS